Controllers films users
Sergej-Nishpal/java-filmorate pull request #2
Opened 2022-07-01 20:05 UTC by Sergej-Nishpal

Выполнено задание по ТЗ 8-го спринта: добавлены модели пользователя и фильма, добавлены контроллеры, выполняется валидация, созданы тесты валидации.

2022-07-02 11:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
аннотации лучше располагать в порядке увеличения их длины, так проще читать код

2022-07-02 11:36 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм с id {} не найден.", film.getId());
можно сделать уровень логирования error для такой ситуации, тем более что выкидывается исключение

2022-07-02 11:37 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +class FilmIdGenerator {
стоит вынести в отдельный класс

2022-07-02 11:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.debug("Обновлен пользователь с id = {}", user.getId());
супер, что в логи везде добавлена информация об объектах, с которыми были произведены действия

2022-07-02 11:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +class UserIdGenerator {
тоже нужно вынести в отдельный файл

2022-07-02 11:39 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
нужно разделить пустой строкой

2022-07-02 11:45 UTC, makholin requested changes
Хорошая работа, много моментов в коде, где все сделано правильно, хотя обычно они не так очевидны для студентов
Видно, что замечания в предыдущих работах вдумчиво разбирались :)

Нужно исправить замечания

2022-07-03 10:54 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Расположил аннотации в порядке увеличения длины.

2022-07-03 10:55 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм с id {} не найден.", film.getId());
Изменил уровень логирования на error везде, где выкидывается исключение.

2022-07-03 10:55 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +class FilmIdGenerator {
FilmIdGenerator вынес в отдельный файл.

2022-07-03 10:56 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +class UserIdGenerator {
UserIdGenerator также вынес в отдельный файл.

2022-07-03 10:57 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
Разделил поля пустыми строками.

2022-07-03 23:20 UTC, makholin approved these changes
Работа принята

2022-07-04 03:39 UTC, merged