Выполнение ТЗ 11-го спринта
Sergej-Nishpal/java-filmorate pull request #5
Opened 2022-08-14 17:51 UTC by Sergej-Nishpal

В проект добавлена возможность работы с базой данных, созданы и настроены хранилища, изменён функционал приложения, написаны интеграционные тесты.

2022-08-15 23:09 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private final MpaStorage mpaStorage;
контроллеры не должны знать о стораджах, они должны вызывать только публичные методы сервисов
а уже сервисы должны внутри себя вызывать публичные методы стораджей

еще один нюанс правильной архитектуры: нижележащие слои не должны ничего знать о вышележащих
например, сервисный слой не должен знать о контроллерах и как-то завязываться на них, сервисы лишь предоставляют публичные методы, а кто их будет использовать - это уже не их зона ответственности

2022-08-15 23:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exception/LikesNotFoundException.java
> +public class LikesNotFoundException extends RuntimeException {
существительные в названиях принято писать в единственном числе, `LikeNotFoundException`

2022-08-15 23:14 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage, FilmLikesStorage {
лучше все таки разделить имплементации интерфейсов на два класса, а не делать этот имплементацией сразу 2х интерфейсов

иначе нарушается принцип Single Responsibility

2022-08-15 23:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage, FilmLikesStorage {
либо, как решение - не выделять методы для добавления лайков в отдельный интерфейс, а сделать эти методы в FilmStorage

в общем, это архитектурное решение остается на твое усмотрение

2022-08-15 23:18 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/InMemoryFriendshipStorage.java
> +    private static final String USER_ID_NOT_FOUND = "Пользователь с id %d не найден";
стоит константу отделить пустой строкой от других полей

2022-08-15 23:19 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +class FilmDbStorageTest {
классы тестов тоже делают public

2022-08-15 23:21 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    @Order(4)
плохо, когда выполнение тестов зависит от порядка их выполнения
лучше писать такие тесты, чтобы при любом порядке выполнения был одинаковый результат

2022-08-15 23:22 UTC, makholin requested changes
Хорошая работа

Нужно исправить замечания

2022-08-16 16:02 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private final MpaStorage mpaStorage;
Убрал стораджи Mpa и Genre из их контроллеров, добавил для них сервисы в качестве промежуточного слоя.
Исправлено.

2022-08-16 16:02 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/exception/LikesNotFoundException.java
> +public class LikesNotFoundException extends RuntimeException {
Исправлено.

2022-08-16 16:02 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage, FilmLikesStorage {
Перенёс эти методы в FilmStorage, лишние классы, интерфейс и тест убрал.
Исправлено.

2022-08-16 16:02 UTC, Sergej-Nishpal commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/InMemoryFriendshipStorage.java
> +    private static final String USER_ID_NOT_FOUND = "Пользователь с id %d не найден";
Исправлено.

2022-08-16 16:02 UTC, Sergej-Nishpal commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +class FilmDbStorageTest {
Здесь плагин SonarLint везде в тестах просит убрать модификатор "public" у классов и методов, ссылаясь на то, что это улучшает читаемость кода: "...it is recommended to use the default package visibility, which improves readability of code." Я им доверился... :)
Исправлено у всех классов с тестами.

2022-08-16 16:03 UTC, Sergej-Nishpal commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    @Order(4)
В ТЗ сказано, что подробнее об этом виде тестирования (интеграционное тестирование) нам расскажут в следующем модуле, но простейшую его реализацию нужно выполнить уже сейчас. И указали, что все публичные методы хранилища должны быть покрыты тестами.
В публичных методах хранилища сейчас есть методы запроса всех сущностей, запроса одной сущности по id, обновления сущности. Если эти методы будут выполняться беспорядочно, то непонятно, что ожидать в результате? Поэтому чтобы протестировать именно все методы хранилищ, был написан скрипт для создания начального состояния БД, а в тестах запрашиваются, добавляются и обновляются сущности. И нашёлся пока только один вариант - задать порядок выполнения тестов. Иначе беспорядок и тесты валятся. :/
Пока не знаю, как это улучшить, чтобы работало без указания порядка.
Обращусь к наставнику за помощью в этом вопросе?

2022-08-16 21:31 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    @Order(4)
в таких тестах обычно в каждом тесте сначла инициализируется база нужными значениями, потом выполняются действия и проверка результатов, а потом бд очищается
еще, как вариант, можно сделать, чтобы бд перед каждым запуском была чистая

но раз тестирование будет в следующих спринтах, то пока можно оставить как есть

2022-08-16 21:32 UTC, makholin approved these changes
Работа принята

2022-08-16 22:59 UTC, Sergej-Nishpal commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorageTest.java
> +    @Order(4)
Понял, спасибо.

2022-08-16 23:00 UTC, merged